services:
  app:
    volumes:
      - ./back:/var/www/html
    ports:
      - "${APP_PORT:-8000}:8000"
    command: php artisan serve --host=0.0.0.0 --port=8000

  postgres:
    ports:
      - "${DB_PORT:-5432}:5432"

  redis:
    ports:
      - "${REDIS_PORT:-6379}:6379"
